<?php
declare(strict_types=1); require_once __DIR__.'/db.php'; require_once __DIR__.'/Mailer.php'; require_once __DIR__.'/session.php';
$message='';$success=false;
function findUser(mysqli $c,string $email):?array{$s=$c->prepare('SELECT id,email FROM users WHERE LOWER(email)=LOWER(?) LIMIT 1');$s->bind_param('s',$email);$s->execute();$r=$s->get_result();$u=$r?$r->fetch_assoc():null;$s->close();return $u?:null;}
if($_SERVER['REQUEST_METHOD']==='POST'){
 $action=$_POST['action']??''; $email=strtolower(trim((string)($_POST['email']??'')));
 if($action==='send_reset_otp'){
  if(!filter_var($email,FILTER_VALIDATE_EMAIL))$message='Please enter a valid email address.'; elseif(!findUser($conn,$email))$message='No account was found for this email address.'; else{$otp=random_int(100000,999999);$_SESSION['reset_otp']=(string)$otp;$_SESSION['reset_email']=$email;$_SESSION['reset_expires_at']=time()+600;$_SESSION['reset_verified']=false;$r=sendOtpEmail($email,$otp,'reset');if(($r['status']??'error')==='success'){$message='OTP sent successfully. Check your email.';$success=true;}else{$message=$r['message']??'Unable to send OTP.';}}
 }elseif($action==='reset_password'){
  $otp=trim((string)($_POST['otp']??''));$password=(string)($_POST['password']??'');$confirm=(string)($_POST['confirm_password']??'');
  $valid=isset($_SESSION['reset_otp'],$_SESSION['reset_email'],$_SESSION['reset_expires_at'])&&hash_equals((string)$_SESSION['reset_otp'],$otp)&&hash_equals((string)$_SESSION['reset_email'],$email)&&time()<=(int)$_SESSION['reset_expires_at'];
  if(!$valid)$message='Invalid or expired OTP.';elseif(!preg_match('/^(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z0-9]).{8,}$/',$password))$message='Password must be at least 8 characters and include an uppercase letter, a number and a special character.';elseif($password!==$confirm)$message='Passwords do not match.';else{$hash=password_hash($password,PASSWORD_DEFAULT);$s=$conn->prepare('UPDATE users SET password=? WHERE LOWER(email)=LOWER(?)');$s->bind_param('ss',$hash,$email);if($s->execute()&&$s->affected_rows>=0){$message='Password reset successfully. You can sign in now.';$success=true;unset($_SESSION['reset_otp'],$_SESSION['reset_email'],$_SESSION['reset_expires_at'],$_SESSION['reset_verified']);}else$message='Unable to reset password.';$s->close();}
 }
}
?><!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><meta name="theme-color" content="#07100d"><title>Forgot Password | DunkHome Kicks</title><link rel="icon" type="image/jpeg" href="image/logo.jpeg"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700;800&family=Playfair+Display:wght@600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"><link rel="stylesheet" href="assets/dunkhome-ui.css"><style>
:root{--bg:#07100d;--white:#f8faf8;--muted:#9baba3;--line:rgba(255,255,255,.1);--green:#79e6aa}*{box-sizing:border-box}body{margin:0;min-height:100vh;color:var(--white);font-family:"DM Sans",sans-serif;background:radial-gradient(circle at 8% 7%,rgba(121,230,170,.13),transparent 27%),linear-gradient(135deg,#06100d,#0a1713 50%,#06100d)}a{color:inherit}.page{width:min(1260px,calc(100% - 34px));min-height:100vh;margin:auto;display:flex;flex-direction:column}.top{height:88px;display:flex;align-items:center;justify-content:space-between}.brand{display:flex;align-items:center;gap:12px;text-decoration:none;font-weight:800;letter-spacing:.16em;text-transform:uppercase}.brand img{width:43px;height:43px;border-radius:13px;object-fit:cover}.brand span{color:var(--green)}main{flex:1;display:grid;place-items:center;padding:18px 0 42px}.shell{width:100%;max-width:560px;padding:35px;border:1px solid var(--line);border-radius:30px;background:rgba(255,255,255,.025);box-shadow:0 35px 100px rgba(0,0,0,.44);backdrop-filter:blur(22px)}.kicker{color:var(--green);font-size:10px;font-weight:800;letter-spacing:.16em;text-transform:uppercase}.title{font:700 40px "Playfair Display",serif;margin:7px 0}.sub{color:var(--muted);line-height:1.7}.message{padding:12px 14px;border-radius:12px;margin:16px 0;color:#ffb0b0;background:rgba(255,123,123,.08);border:1px solid rgba(255,123,123,.2)}.message.success{color:#9ff0bd;background:rgba(121,230,170,.08);border-color:rgba(121,230,170,.2)}label{display:block;font-size:12px;font-weight:800;margin:18px 0 8px}input{width:100%;height:52px;border-radius:13px;border:1px solid var(--line);background:rgba(0,0,0,.18);color:var(--white);padding:0 14px;outline:none}input:focus{border-color:rgba(121,230,170,.5)}.row{display:grid;grid-template-columns:1fr 1fr;gap:12px}.btn{margin-top:18px;width:100%;height:50px;border:0;border-radius:13px;background:linear-gradient(135deg,#4ade80,#22c55e);color:#041008;font-weight:800;cursor:pointer}.links{display:flex;justify-content:space-between;margin-top:18px;color:var(--muted);font-size:12px}@media(max-width:600px){.shell{padding:24px}.row{grid-template-columns:1fr}}
</style></head><body><div class="page"><header class="top"><a class="brand" href="index.php"><img src="image/logo.jpeg" alt="DunkHome Kicks">dunkhome_<span>kicks</span></a><a href="SignIn.php">Sign in</a></header><main><section class="shell"><div class="kicker">Account recovery</div><h1 class="title">Forgot password?</h1><p class="sub">Enter your registered email. We will send a 6-digit OTP, then you can set a new password on this page.</p><?php if($message):?><div class="message <?=$success?'success':''?>"><?=h($message)?></div><?php endif;?><?php if(!$success || !empty($_SESSION['reset_otp'])):?><form method="post"><input type="hidden" name="action" value="send_reset_otp"><label>Email address</label><input type="email" name="email" value="<?=h((string)($_POST['email']??$_SESSION['reset_email']??''))?>" required><button class="btn">Send OTP</button></form><?php endif;?><form method="post"><input type="hidden" name="action" value="reset_password"><label>Email address</label><input type="email" name="email" value="<?=h((string)($_SESSION['reset_email']??$_POST['email']??''))?>" required><div class="row"><div><label>OTP</label><input type="text" name="otp" inputmode="numeric" maxlength="6" pattern="\d{6}" required></div><div><label>New password</label><input type="password" name="password" required></div></div><label>Confirm new password</label><input type="password" name="confirm_password" required><button class="btn">Verify OTP &amp; Reset Password</button></form><div class="links"><a href="SignIn.php">← Back to sign in</a><a href="index.php">Home</a></div></section></main></div><script src="assets/dunkhome-ui.js" defer></script></body></html>
